WebProje/WebProje/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.DAL;
using WebProje.Models;
using WebProje.Models.ViewModels;

namespace WebProje.Controllers
{
    public class AdminController : Controller
    {
        VeriContext db = new VeriContext();
        // GET: Admin
        [Authorize]
        public ActionResult AdminIndex()
        {
            var model = new AdminViewModel()
            {
                Haber = db.Haberler.ToList(),
                Uye = db.Uyeler.ToList(),
                Admin = db.Adminler.ToList(),
                Yorum = db.Yorumlar.ToList()   
            };
           
            return View(model);
        }
    }
}

WebProje/WebProje/Controllers/GirisYapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using WebProje.DAL;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class GirisYapController : Controller
    {
        VeriContext db = new VeriContext();
        // GET: GirisYap
        [HttpGet]
        public ActionResult UyeGiris()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult UyeGiris(Uye model)
        {
            var kullanici = db.Uyeler.FirstOrDefault(x => x.EPosta == model.EPosta && x.Sifre == model.Sifre);
            if (kullanici != null)
            {
                FormsAuthentication.SetAuthCookie(kullanici.KulAdi, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Mesaj = "EPosta veya Şifre Hatalı";
                return View();
            }
           
        }
        [HttpGet]
        public ActionResult AdminGiris()
        {
            return View();
        }
   
        [HttpPost]
        public ActionResult AdminGiris(Admin model)
        {
            var kullanici = db.Adminler.FirstOrDefault(x=>x.EPosta==model.EPosta && x.Sifre==model.Sifre);
            if (kullanici!=null)
            {
                FormsAuthentication.SetAuthCookie(kullanici.KulAdi,false);
                return RedirectToAction("AdminIndex","Admin");
            }
            else
            {
                ViewBag.Mesaj = "EPosta veya Şifre Hatalı";
                return View();
            }
            
        }
        public ActionResult Cikis()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index","Home",null);
        }
    }
}

WebProje/WebProje/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProje.DAL;
using WebProje.Models;
using PagedList;

namespace WebProje.Controllers
{
    [Authorize]
    public class HaberController : Controller
    {
        private VeriContext db = new VeriContext();

        // GET: Haber
      
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.BaslikSortParm = String.IsNullOrEmpty(sortOrder) ? "AzalanBaslik" : "";
            ViewBag.TarihSortParm = sortOrder == "Tarih" ? "AzalanTarih" : "Tarih";
            ViewBag.OkunmaSortParm = sortOrder == "Okunma" ? "AzalanOkunma" : "Okunma";
            ViewBag.OnaySortParm = sortOrder == "Onay" ? "AzalanOnay" : "Onay";
            ViewBag.KategoriSortParm = sortOrder == "Kategori" ? "AzalanKategori" : "Kategori";
            ViewBag.EkleyenSortParm = sortOrder == "Ekleyen" ? "AzalanEkleyen" : "Ekleyen";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var haberler = from s in db.Haberler
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                haberler = haberler.Where(s => s.Baslik.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Onay":
                    haberler = haberler.OrderBy(s => s.Onay);
                    break;
                case "AzalanOnay":
                    haberler = haberler.OrderByDescending(s => s.Onay);
                    break;
                case "Kategori":
                    haberler = haberler.OrderBy(s => s.Kategori);
                    break;
                case "AzalanKategori":
                    haberler = haberler.OrderByDescending(s => s.Kategori);
                    break;
                case "Ekleyen":
                    haberler = haberler.OrderBy(s => s.Admin.Ad);
                    break;
                case "AzalanEkleyen":
                    haberler = haberler.OrderByDescending(s => s.Admin.Ad);
                    break;
                case "Okunma":
                    haberler = haberler.OrderBy(s => s.OkunmaSayisi);
                    break;
                case "AzalanOkunma":
                    haberler = haberler.OrderByDescending(s => s.OkunmaSayisi);
                    break;
                case "AzalanBaslik":
                    haberler = haberler.OrderByDescending(s => s.Baslik);
                    break;
                case "Tarih":
                    haberler = haberler.OrderBy(s => s.HaberTarihi);
                    break;
                case "AzalanTarih":
                    haberler = haberler.OrderByDescending(s => s.HaberTarihi);
                    break;
                default:  // Name ascending 
                    haberler = haberler.OrderBy(s => s.Baslik);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(haberler.ToPagedList(pageNumber, pageSize));
        }
        /* public ActionResult Index(string currentFilter, string searchString, int? page)
         {
             if (searchString != null)
             {
                 page = 1;
             }
             else
             {
                 searchString = currentFilter;
             }

             ViewBag.CurrentFilter = searchString;

             var haberler = from s in db.Haberler
                            select s;
             if (!String.IsNullOrEmpty(searchString))
             {
                 haberler = haberler.Where(s => s.Baslik.Contains(searchString));
             }
             int pageSize = 3;
             int pageNumber = (page ?? 1);
             return View(haberler.ToPagedList(pageNumber, pageSize));
             //var haberler = db.Haberler.Include(h => h.Admin);
             //return View(haberler.ToList());
         }*/

        // GET: Haber/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haber haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }
            return View(haber);
        }

        // GET: Haber/Create
        public ActionResult Create()
        {
            ViewBag.AdminID = new SelectList(db.Adminler, "AdminID", "Ad");
            return View();
        }

        // POST: Haber/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HaberID,AdminID,Icerik,Foto,Kategori,HaberTarihi,Onay,Baslik,OkunmaSayisi")] Haber haber)
        {
            if (ModelState.IsValid)
            {
                haber.HaberTarihi = DateTime.Now;
                haber.OkunmaSayisi = 0;
                db.Haberler.Add(haber);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdminID = new SelectList(db.Adminler, "AdminID", "Ad", haber.AdminID);
            return View(haber);
        }

        // GET: Haber/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haber haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdminID = new SelectList(db.Adminler, "AdminID", "Ad", haber.AdminID);
            return View(haber);
        }
        
        public ActionResult Delete(int? id)
        {
            Haber haber = db.Haberler.Find(id);
            db.Haberler.Remove(haber);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProje/WebProje/Controllers/TakimBransController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WebProje.DAL;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class TakimBransController : Controller
    {
        // GET: TakimBrans
        VeriContext db = new VeriContext();
        public ActionResult Index(int? SayfaNo,Takim takim,Kategoriler brans)
        {
            int _sayfaNo = SayfaNo ?? 1;
            
            
                var haberler = db.Haberler.OrderByDescending(x => x.HaberID).Where(x => (x.Takim == takim && x.Kategori == brans)).ToPagedList<Haber>(_sayfaNo,9);
                return View(haberler);
            
            
        }
    }
}

WebProje/WebProje/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Haber Sitesi</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/modern-business.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/Home/Index">HABER SİTESİ</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @WebProje.Resources.Kaynak.Futbol
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                            @Html.ActionLink("Fenerbahçe", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Fenerbahce, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Galatasaray", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Galatasaray, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Beşiktaş", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Besiktas, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Trabzonspor", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Trabzonspor, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink(@WebProje.Resources.Kaynak.MilliTakim, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.MilliTakim, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @WebProje.Resources.Kaynak.Basketbol
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            @Html.ActionLink("Fenerbahçe", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Fenerbahce, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Anadolu Efes", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Efes, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink(@WebProje.Resources.Kaynak.MilliTakim, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.MilliTakim, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })
                        </div>
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink(@WebProje.Resources.Kaynak.DigerTakimlar, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Diger, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item">

                        @Html.ActionLink(@WebProje.Resources.Kaynak.Haberler, "Index", "Haber", null, new { @Class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Uye/Index">@WebProje.Resources.Kaynak.Uyeler</a>
                    </li>
                    <li class="nav-item">

                        @Html.ActionLink("Panel", "AdminIndex", "Admin", null, new { @Class = "nav-link" })
                    </li>
                    <li class="nav-item">

                        @Html.ActionLink(@WebProje.Resources.Kaynak.CikisYap, "Cikis", "GirisYap", null, new { @Class = "nav-link" })
                    </li>
</div>
        </div>
    </nav>

    @RenderBody()


    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright © HAKME @DateTime.Now.Year</p>
        </div>
    </footer>
</body>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</html>

WebProje/WebProje/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Haber Sitesi</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/modern-business.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/Home/Index">HABER SİTESİ</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        @*<li class="nav-item">

                @Html.ActionLink(@WebProje.Resources.Kaynak.Dil, "Index", "Language", null, new { @Class = "nav-link" })
            </li>*@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @WebProje.Resources.Kaynak.Futbol
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                            @Html.ActionLink("Fenerbahçe", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Fenerbahce, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Galatasaray", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Galatasaray, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Beşiktaş", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Besiktas, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Trabzonspor", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Trabzonspor, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink(@WebProje.Resources.Kaynak.MilliTakim, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.MilliTakim, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @WebProje.Resources.Kaynak.Basketbol
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            @Html.ActionLink("Fenerbahçe", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Fenerbahce, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Anadolu Efes", "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Efes, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })
                            @Html.ActionLink(@WebProje.Resources.Kaynak.MilliTakim, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.MilliTakim, brans = WebProje.Models.Kategoriler.Basketbol }, new { @class = "dropdown-item" })

                        </div>
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink(@WebProje.Resources.Kaynak.DigerTakimlar, "Index", "TakimBrans", new { takim = WebProje.Models.Takim.Diger, brans = WebProje.Models.Kategoriler.Futbol }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @WebProje.Resources.Kaynak.Iletisim
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            <a class="dropdown-item" href="full-width.html">Instagram</a>
                            <a class="dropdown-item" href="sidebar.html">Twitter</a>
                            <a class="dropdown-item" href="faq.html">Facebook</a>
                            <a class="dropdown-item" href="404.html">Gmail</a>
                        </div>
                    </li>
                    @{
                        if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">

                                @Html.Label(@WebProje.Resources.Kaynak.GirisYapilanKullanici + " " + HttpContext.Current.User.Identity.Name, new { @Class = "nav-link" })
                            </li>
                            <li class="nav-item">

                                @Html.ActionLink(@WebProje.Resources.Kaynak.CikisYap, "Cikis", "GirisYap", null, new { @Class = "nav-link" })
                            </li>


                        }
                        else
                        {
                            <li class="nav-item">

                                @Html.ActionLink(@WebProje.Resources.Kaynak.KayitOl, "Create", "KayitOl", null, new { @Class = "nav-link" })
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @WebProje.Resources.Kaynak.Giris
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                                    @Html.ActionLink(@WebProje.Resources.Kaynak.UyeGirisi, "UyeGiris", "GirisYap", null, new { @Class = "dropdown-item" })
                                    @Html.ActionLink(@WebProje.Resources.Kaynak.AdminGirisi, "AdminGiris", "GirisYap", null, new { @Class = "dropdown-item" })

                                </div>
                            </li>
                        }
                    }
                    <li class="nav-item">
                        <a href="@Url.Action("DilDegistir", "Home", new { LanguageAbbrevation = "tr" })"><img class="" style="position:relative; height: 25px; width: 25px;" src="~/Content/Images/tr.png" alt="Türkçe"></a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("DilDegistir", "Home", new { LanguageAbbrevation = "en" })"><img class="" style="position:relative;height: 25px; width: 25px;" src="~/Content/Images/en.jpg" alt="English"></a>
                    </li>




                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()


    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright © HAKME @DateTime.Now.Year</p>
        </div>
    </footer>
</body>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</html>